apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: labv1d2cu-python
  janus-idp.io/tekton: labv1d2cu-python
  backstage.io/kubernetes-id: labv1d2cu-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: labv1d2cu-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
