apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: labv1d2cu-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: labv1d2cu-python 
  name: labv1d2cu-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: labv1d2cu-python 
